### ISSUE TITLE
Allow chrome to sync extension data

### ISSUE THREAD

**Issue by HaydnDias** [deanoemcke/spaces#9] opened 2018-03-27 09:59 UTC
Are there any plans or is it possible to get this extension to sync using google drive or some other cloud based system? It'd be super useful as I work between a range of different systems for work and being able to take my tab work spaces with me would be a god send.

**Comment by deanoemcke** [comment] 2019-01-26 11:51
Duplicate of: https://github.com/deanoemcke/spaces/issues/5

**Closed as completed by deanoemcke** 2019-01-26 11:51 UTC
Labels: duplicate
